### ISSUE TITLE
Use Typescript Language Services

### ISSUE THREAD

**Issue by chadhietala** [tildeio/broccoli-typescript-compiler#19]
Currently this plugin does not exam the entire TypeScript program and I believe this is the cause of the pain in Glimmer where it appears the program has no type errors, but when you go to CI the build fails. The angular team has their own [TS plugin](https://github.com/angular/angular/blob/master/tools/broccoli/broccoli-typescript.ts) that does incremental rebuilds of the program. I think we need to either a) ask them to extract this or b) incorporate their learnings.

**Comment by rwjblue** [comment]
Per https://github.com/angular/angular/blob/master/LICENSE (MIT), we can do the extraction and use their implementation here.

**Comment by winding-lines** [comment]
I would like to help, some questions:
- any advice on how to proceed
- will this work allow me to use this broccoli plugin in ember-cli

**Comment by rwjblue** [comment]
This broccoli plugin is used by https://github.com/locks/ember-cli-typescript to provide support to ember-cli apps.

**Comment by winding-lines** [comment]
I have been playing with the angular code. They are trying to solve the bigger problem of providing type/typing information for their dependencies and their own code, in addition to just integrating typescript. I have not looked at the type providers in the last 6 mo and it seems that Microsoft is pushing forward the @types npm scope as a place to centralize all of the information for the ecosystem. It looks very promising to me, you only use npm to manage this additional info instead of tds or typing.

As part of this exploration I found that the @types for fs-extra, for example, requires typescript 1.9.0-dev. As I mentioned earlier my goals are to allow type checking at the Ember app level, similar to what angular is doing. The current plugin is focussed more on supporting arbitrary typescript versions, in a given range, and uses peerDependencies.

Are you ok moving the plugin to support just 1.9.0-dev, as a dependency, or should I start a new plugin which is more inline with my needs?

Thanks for your feedback.

**Comment by rwjblue** [comment]
@tomdale points out that the official docs include details on using language services for incremental builds: 

https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services

**Comment by winding-lines** [comment]
Yeap. :)

**Comment by winding-lines** [comment]
I spent some hours(sss) this week extracting code from the angular codebase. My goals are:
- get the dev experience right, for example:
  - after setup just rename files to .ts to enable type checking
  - adding dependencies should bring in .d.ts files automatically
- re-use which ever code makes sense from the angular database

Currently I am not focussed on:
- support non-ember projects
- support arbitrary typescript compilers (I need 2.0.0-dev for @types support)

I've created a handful of repos and after things stabilize we can figure out what goes where.
- demo app https://github.com/winding-lines/ember-app-typify
- addon https://github.com/winding-lines/ember-cli-typify
- plugin https://github.com/winding-lines/broccoli-typify
- ts2.0 compatible ember d.ts file https://github.com/winding-lines/at-types-ember

My approach is to have typescript do only the type related processing and generate es5/6. Then the ember pipeline should transpile down to browser level. 

**Status**

Tests pass in plugin and addon, failing in app. I am really puzzled why the generated code is different for ts-component.js in the two scenarios:
- in the addon `ember test` transpiles to the usual define()
- in the context of the app `ember build` ts-component.js is concatenated as es5 in dist/assets/ember-app-typify.  

**Help?**

Maybe the babel addon runs after typescript in the former but not in the latter? Any thoughts on how to debug further?

**Comment by winding-lines** [comment]
FYI, `ember server` now working in https://github.com/winding-lines/ember-app-typify.

I will install this in an actual app and iterate some more.

**Comment by tomdale** [comment]
@winding-lines This is so awesome, thank you for working on this.

**Comment by tomdale** [comment]
FWIW I think all or almost all of the TypeScript projects used by Ember are using TypeScript nightlies. I don't think you need to worry about backwards compatibility with older TS versions, especially if it makes things more difficult.

**Comment by locks** [comment]
@winding-lines talk to me on Slack, this interests me for the addon that @rwjblue mentioned.

**Comment by winding-lines** [comment]
@locks I am moving a complex internal ember app to typescript. The broccoli-typify api is in flux at this point, the resolver is still changing. It's not just about getting .ts files to transpile, it is also about how do you get external libraries (and ember.d.ts) integrated.

I am using https://github.com/winding-lines/ember-app-typify for some of the use cases. You can see there my current approach to typecheck '/config/environment'. I hope to finish the first pass over this weekend and then we can start thinking about the API.

**Comment by winding-lines** [comment]
@locks made some awesome progress yesterday, I have the internal application building and serving :)

The current open issue is around rebuilds(). The issue can be seen on https://github.com/winding-lines/ember-app-typify. The first `ember serve` works, then editing  ts-component.ts leads to some error due to some input file crossing. It seems that ember-cli instantiates two ember-cli-typify addons, one for app and one for tests.The first time build works fine but then on rebuild the inputs get crossed and the wrong instance of ember-cli-typify gets the input tree. Or something :-)

```
Error: [DiffingTSCompiler]: Typescript found the following errors:
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/app.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/components/app-version.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/components/ts-component.ts' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/initializers/app-version.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/initializers/container-debug-adapter.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/initializers/export-application-global.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/lib/some-const.ts' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/resolver.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/router.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/services/ajax.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/services/lyft.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/templates/application.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
  Error: File '/Users/wl/ts/ember-app-typify/tmp/tree_stabilizer-output_path-x3ZEfVvD.tmp/ember-app-typify/templates/components/ts-component.js' is not under 'rootDir' '/Users/wl/ts/ember-app-typify/tmp/funnel-output_path-2dp5qvdy.tmp'. 'rootDir' is expected to contain all source files.
    at DiffingTSCompiler.rebuild (/Users/wl/ts/ember-app-typify/node_modules/ember-cli-typify/node_modules/broccoli-typify/dist/broccoli-typescript.js:128:29)
    at DiffingPluginWrapper.rebuild (/Users/wl/ts/ember-app-typify/node_modules/ember-cli-typify/node_modules/broccoli-typify/dist/diffing-broccoli-plugin.js:91:45)
    at /Users/wl/ts/ember-app-typify/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/api_compat.js:42:21
    at lib$rsvp$$internal$$tryCatch (/Users/wl/ts/ember-app-typify/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/wl/ts/ember-app-typify/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/wl/ts/ember-app-typify/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/wl/ts/ember-app-typify/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by winding-lines** [comment]
Guys, I am pretty happy with the current status of broccoli-typify. The type defs are properly located both by the plugin and the IDE. 

In terms of integration the API is currently not the same. Do you want me to add support for the current API and just smash my current code on top of this plugin? Or do you want to keep them separate?

**Comment by locks** [comment]
@winding-lines are you on Slack? I'd like to chat about this, I need some pointers if I'm to improve my addon.

**Comment by tomdale** [comment]
@winding-lines Hey, where did you land on this? We have a non-Ember Broccoli project using Glimmer 2 and we're getting owned by the current limitations of the Broccoli plugin. Would love to test it out in our app if you have a Broccoli plugin that needs testing.

**Comment by winding-lines** [comment]
Yes, let's test it in your app and then merge. What's the github project?

**Comment by krisselden** [comment]
@winding-lines @tomdale I have a PR to the tilde one that fixes the same issues and has stable output which will work better with other downstream broccoli plugins. We should try to unify efforts

**Comment by winding-lines** [comment]
Kris,

I took the angular code that Chad pointed me to. It also stabilizes
funnels. Let's connect and compare.

**Comment by stefanpenner** [comment]
> I took the angular code that Chad pointed me to. It also stabilizes

Last I checked this wasn't the case, maybe they fixed it since the last time I looked?

**Comment by winding-lines** [comment]
Talked to Kris, I will test his PR code and merge any changes I need :)
