### ISSUE TITLE
Thanks and Future Plans?

### ISSUE THREAD

**Issue by philipbjorge** [tildeio/broccoli-typescript-compiler#2]
I appreciate you writing this package -- It looks to be the best option to use typescript with broccoli available, even if it is a WIP.

I've used it to put together the following repo which I hope to test and improve on in the coming weeks to see what Ember TS integration could look like.

https://github.com/philipbjorge/ember-cli-typescript
(Any tips would be greatly appreciated on this as I'm new to the ember ecosystem)

Is there anything on the roadmap for this package?
Also, is this being used internally at tilde?

**Comment by stefanpenner** [comment]
I would recommend giving ember-cli-Babel a quick scan, as it does nearly the same thing

**Comment by chancancode** [comment]
What Stefan said; in fact it is literally a fork of the Babel plugin :)
