### ISSUE TITLE
should implement using LanguageService \w getScriptVersion for more performant builds

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/broccoli-typescript-compiler#27]
https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services

we should be sure to correctly handle deletes.

This should allow us to do more performant incremental builds

**Comment by krisselden** [comment]
I have many doubts this is doing anything under the hood differently than I'm already doing but should be easy enough to try and at least I can get rid of the source map cache, but don't get your hopes up.

**Comment by stefanpenner** [comment]
Maybe, but I will investigate this. If that it true, then the underlying TS module itself may want to be improved. Between rebuilds it is currently doing a very large amount of identical work.

**Comment by stefanpenner** [comment]
@krisselden specifically, the current approach does cache the parsing. But all the typechecking is not cached and is currently dominating rebuilds (800ms for es6-promise), which seems fishy no?

**Comment by krisselden** [comment]
Sure but you are missing what I'm saying, it still recreates the program for a change. I linked the code from the language services, it builds the program again from the old program when a file in the project changes version, which is what's happening now

**Comment by stefanpenner** [comment]
@krisselden so your saying, even with a language service, Typescript is quite slow?

e.g. nearly 1s to rebuild a small 2.4k gziped lib like es6-promise?

**Comment by stefanpenner** [comment]
> Sure but you are missing what I'm saying, it still recreates the program for a change

I think we can do better then this.

I hacked together an incremental version, that still does "whole code" optimizations like inlining enums cross module etc. It seems to perform about 8x -> 10x faster on es6-promise, then the current approach.

It seems like, although TS has all the required machinery it chooses a more conservative and slow approach by default. 

I may be missing something... but incremental approach appears to be as just as safe, just much faster. The odd thing is, the incremental approach also seems faster for initial build, which leads me to believe it is not doing the same thing... but the output (and warnings) appear the same.

It also seems like the TS internals started down this path, but never completed.. 

When you are in-town we should sit down, and figure out what I'm missing.

**Comment by krisselden** [comment]
ok, I'm missing something, the language services seems to hit https://github.com/Microsoft/TypeScript/blob/edd8eb8733c965b0145267a6d2cf3b39705639eb/src/services/services.ts#L1073 for any change in input.  That is the same approach that was my point, is I followed what tsc --watch does for incremental builds and the above looks same.

I just want to understand what is different.

**Comment by krisselden** [comment]
ok, it does recreate program but the document registry is what shares info between the two, I'm puzzled then why tsc --watch doesn't do this.

**Comment by krisselden** [comment]
this is the key difference, is the document registry https://github.com/Microsoft/TypeScript/blob/edd8eb8733c965b0145267a6d2cf3b39705639eb/src/services/services.ts#L1146 which I think is being shared between your two broccoli nodes which is why it is faster

**Comment by stefanpenner** [comment]
> ok, it does recreate program but the document registry is what shares info between the two, I'm puzzled then why tsc --watch doesn't do this.

ya, unknown. I suspect if they did, many would be happier...

**Comment by krisselden** [comment]
LanguageService had issues and internally uses the DocumentRegistry and the CompilerHost so changed back to the CompilerHost and added in using the DocumentRegistry.
