### ISSUE TITLE
JS files are clobbered

### ISSUE THREAD

**Issue by pittst3r** [tildeio/broccoli-typescript-compiler#32]
It appears this may be intentional based on the last paragraph in the readme and [this comment](https://github.com/tildeio/broccoli-typescript-compiler/blob/695d0aead3cb270ad231edfba378c3ef3c3577c9/index.js#L6), but it seems like this is [undesirable behavior](https://github.com/glimmerjs/glimmer-application-pipeline/pull/2#issuecomment-277488748).

cc @rwjblue @dgeb

**Comment by rwjblue** [comment]
Thanks for making an issue on this here!

Happy to have a quick meeting to discuss if you feel strongly @krisselden...

**Comment by krisselden** [comment]
`allowJs` doesn't mean let me import js without complaints, it means you want ts compiler to transpile your js and emit it.

I do want to allow passthrough, but when I do, it will only passthrough unused input, js that you ask the compiler to transpile will count as "used" input and the transpiled output will be emitted.

I think 'allowJs' is misunderstood.  External js imports are already allowed as long as they are external and you allow implicit any, if  you don't have implicit any then they need a declaration file.

**Comment by pittst3r** [comment]
> it means you want ts compiler to transpile your js and emit it.

Yes, that's how I understand it. And that's not happening with the `allowJs` option. If I include a js file in the input tree, and the js file is included per the tsconfig, the file is not emitted. I have not checked with v2 yet though.

> I think 'allowJs' is misunderstood. External js imports are already allowed as long as they are external and you allow implicit any, if you don't have implicit any then they need a declaration file.

Not what I'm trying to do. Just trying to be able to mix js and ts files in the source and have them all emit as js files.

**Comment by krisselden** [comment]
@robbiepitts that intentionally does not work with the legacy filter pipeline because the it filters out js from the input like the old filter did.
