### ISSUE TITLE
Uses cached version on first rebuild

### ISSUE THREAD

**Issue by mntnoe** [tildeio/broccoli-typescript-compiler#33]
I am experiencing the following:

When running broccoli in watch mode, the first time I edit a file, the change is not reflected in the output of the build. I can trace in the /tmp/broccoli-*/out-* dirs that the broccoli pipeline has the updated file in all node output dirs until broccoli-typescript-compiler. Subsequent edits work fine.

Example: Suppose BTC compiles file x.ts containg `foo: number = 1` to `foo = 1`. Then when first starting broccoli in watch mode, it will correctly output `foo = 1`. We make an edit:

```foo: number = 2```

but BTC  still outputs `foo = 1`. Now we make a second edit:

```foo: number = 3```

and BTC now correctly outupts `foo = `.

Any ideas what can be wrong, and if there is a fix or a workaround?

**Comment by mntnoe** [comment]
I should add that I have tested it both with the most recent release (1.0.1) and with the language service PR merged in.

**Comment by krisselden** [comment]
@mntnoe any chance you can make a failing test?

**Comment by ColorYak** [comment]
I'm fully booked this week, but I will try to have a look at it next week.

**Comment by mntnoe** [comment]
(deleted previous comment, I was on wrong github user)

I'm fully booked this week, but I will try to have a look at it next week.

**Comment by mntnoe** [comment]
I have made a minimal repo that is able to reproduce the problem:

https://github.com/mntnoe/btc-caching-demo

Steps to reproduce:

- Install dependencies: `yarn`

- Run broccoli in watch mode: `yarn run serve`

- Observe that the module `/tmp/broccoli-<id>/out-1-broccoli_typescript_compiler/index.js` exports the value `'foo'`

- Change the file `src/index.ts` to contain `export const value: string = 'bar'`

- Observe that the module `/tmp/broccoli-<id>/out-1-broccoli_typescript_compiler/index.js` STILL exports the value `'foo'`

- Change the file `src/index.ts` to contain `export const value: string = 'baz'`

- Observe that the module `/tmp/broccoli-<id>/out-1-broccoli_typescript_compiler/index.js` now correctly exports the value `'baz'`
