### ISSUE TITLE
Support other lib files

### ISSUE THREAD

**Issue by davewasmer** [tildeio/broccoli-typescript-compiler#35]
It seems like the way the default lib file is handled that targets newer than ES2015/ES6 are not supported. This also seems to be a problem for any manually specified `lib` files in the tsconfig. For example, if I set my project target to ES2016, then Typescript will attempt to include additional lib files beyond the single [defaultLibFileName](https://github.com/tildeio/broccoli-typescript-compiler/blob/master/src/source-cache.ts#L18). Since these additional lib files don't match the name of the default lib, the SourceCache will [attempt to load the from the input broccoli tree](https://github.com/tildeio/broccoli-typescript-compiler/blob/master/src/source-cache.ts#L46) rather than the Typescript module's lib folder.

I'm not sure the best way to tackle this. I have a working patch that just scans `path.dirname(defaultLibFileName)`, and if any requested files match a lib file, it uses that lib file. Of course, this doesn't handle filename collisions between the Typescript lib files and the Broccoli input files. One option would be to check both and give precedence to the Broccoli input files.

Figured I'd file this first to see if I was missing something. Happy to PR my suggested patch, or something else.

**Comment by davewasmer** [comment]
Looks like this is supposed to be fixed with with #41?

**Comment by krisselden** [comment]
@davewasmer yes, it is fixed in the beta just working out some issues.  You can try it out by using `npm install broccoli-typescript-compiler@beta`
