### ISSUE TITLE
Support passthrough without filtering...

### ISSUE THREAD

**Issue by rwjblue** [tildeio/broccoli-typescript-compiler#38]
Given the following input files:

```
DEBUG-handlebars-output
└── src
    ├── index.ts
    └── ui
        ├── components
        │   └── foo-bar.js
        └── index.html
```

Using `require('broccoli-typescript-compiler').typescript`, the following is the output:

```
DEBUG-rollup-input-tree
└── index.js
```

---

If we use the [default export](https://github.com/tildeio/broccoli-typescript-compiler/blob/master/index.js#L7-L23) (e.g. `require('broccoli-typescript-compiler')`) directly, we end up running two pretty costly `Funnel`'s to `include: ['**.ts']` (in typescript tree) and `exclude: ['**.ts']` (from passthrough tree) then merge the two back together.

Doing `include` / `exclude` operations like this forces us to stat all of the input tree (which is often very large, and includes `node_modules`).

Opening this issue to start the dialogue on the best path forward...

**Comment by tomdale** [comment]
@rwjblue I think this is addressed in @krisselden's latest changes, right? OK to close?
