### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by chriskrycho** [tildeio/broccoli-typescript-compiler#43]
Looks like quite a bit has changed since last October, including [a change](https://github.com/tildeio/broccoli-typescript-compiler/pull/34) which I *believe* fixes the root cause of [an issue](https://github.com/emberwatch/ember-cli-typescript/issues/38) I'm having on [ember-cli-typescript](https://github.com/emberwatch/ember-cli-typescript). Can we please get a fresh version pushed to npm? Thanks!

**Comment by stefanpenner** [comment]
@krisselden anything blocking release?

**Comment by tomdale** [comment]
Looks like @krisselden released v2.0.0 last week. @chriskrycho Any updates on if this addressed your issue?

**Comment by chriskrycho** [comment]
It did—and Ember-CLI-TypeScript is chugging along nicely as a result!
