### ISSUE TITLE
Semver dependency on typescript in minor range is a breaking change: TypeError: getFileSystemEntries is not a function

### ISSUE THREAD

**Issue by theseyi** [tildeio/broccoli-typescript-compiler#49]
broccoli-typescript-compiler has a permissive package.json that depends on TypeScript version `^2.3.3`. This `minor` range dependency currently allows Yarn to install TS 2.5.0 which is at release candidate `rc` stage. 

https://registry.yarnpkg.com/typescript revision: 1052-fb9eebd5b091190020c3c186ce299827
```
{
latest: "2.4.2",
next: "2.6.0-dev.20170817",
beta: "2.0.0",
rc: "2.5.0",
insiders: "2.4.2-insiders.20170719"
},
```
Unfortunately, this actually breaks the broccoli build step because there is an incompatible api change:
in typescript.js, the function signature `matchFiles` in @2.5.0 rc, accepts an additional argument `depth`:
```javascript
function matchFiles(path, extensions, excludes, includes, useCaseSensitiveFileNames, currentDirectory, depth, getFileSystemEntries) {
...
}
```
https://github.com/Microsoft/TypeScript/blob/v2.5-rc/src/compiler/core.ts#L2073
versus the current/latest @2.4.2 signature
```javascript
function matchFiles(path, extensions, excludes, includes, useCaseSensitiveFileNames, currentDirectory, getFileSystemEntries) {
...
}
```
https://github.com/Microsoft/TypeScript/blob/v2.4.2/src/compiler/core.ts#L2023
You'll notice that the `depth` parameter was not previuosly present

This cause the broccoli build to throw:

`TypeError: getFileSystemEntries is not a function`

EDIT: updated with TS repo source links

**Comment by rwjblue** [comment]
I reported the breaking change to the typescript folks in https://github.com/Microsoft/TypeScript/issues/17891. However, we will still have to address to mitigate failures for all of our users.  

This repeated pattern of breaking changes within the same major version in `typescript` is quite annoying... 😡

**Comment by theseyi** [comment]
Thanks for taking a look @rwjblue . Speaking of failures for users, would the PR patch #50 be a quick way to mitigate the failures. At least until a lasting resolution is made? I assume other users have a critical dependency on this since it will break all continuous integration builds, and any clean builds
