### ISSUE TITLE
Support for TypeScript 2.6.x

### ISSUE THREAD

**Issue by theseyi** [tildeio/broccoli-typescript-compiler#53]
Currently b-t-c supports  TypeScript ~2.5.2. The latest version of TS is 2.6.1. 
Upgrading to this version is a breaking change but one that would need to be supported soon to take advantage of new features like strict parameter contravariance with `strictFunctionTypes`, `// @ts-ignore` pragma, etc

**Comment by krisselden** [comment]
Have you tried bumping it and bumping the submodule and running the tests?

**Comment by chriskrycho** [comment]
FWIW, I'm using TS 2.6 with current broccoli-typescript-compiler without issue, at least so far.

**Comment by theseyi** [comment]
I'll try bumping the submodule, just bumping the main repo was failing when I attempted to

**Comment by theseyi** [comment]
Test's pass, the error encountered when running `npm run-script build` is:
```
lib/compiler.ts(116,35): error TS2345: Argument of type 'ReadonlyArray<Diagnostic>' is not assignable to parameter of type 'Diagnostic | Diagnostic[] | undefined'.
  Type 'ReadonlyArray<Diagnostic>' is not assignable to type 'Diagnostic[]'.
    Property 'push' is missing in type 'ReadonlyArray<Diagnostic>'.
lib/compiler/output-patcher.ts(51,53): error TS2345: Argument of type '(a: Entry, b: Entry) => boolean' is not assignable to parameter of type '((a: Entry, b: Entry) => {}) | undefined'.
  Type '(a: Entry, b: Entry) => boolean' is not assignable to type '(a: Entry, b: Entry) => {}'.
    Types of parameters 'a' and 'a' are incompatible.
      Type 'WalkSync.Entry' is not assignable to type 'Entry'.
        Property 'checksum' is missing in type 'Entry'.
```
