### ISSUE TITLE
Release 2.1.1 with TS 2.6 support?

### ISSUE THREAD

**Issue by chriskrycho** [tildeio/broccoli-typescript-compiler#55]
Since @theseyi kindly did the work to get TS 2.6 integration working, can we get a 2.1.1 with that support rolled in? I need it for things like `// @ts-ignore` in my app using ember-cli-typescript, and would prefer *not* to point that addon at master. 😬 

Thanks!

**Comment by krisselden** [comment]
will do

**Comment by krisselden** [comment]
broccoli-typescript-compiler 2.1.1 published 🎉

**Comment by chriskrycho** [comment]
Thanks so much! I'll update ember-cli-typescript to use it over the weekend!
