### ISSUE TITLE
Usage in libkit doesn't generate sourcemaps correctly

### ISSUE THREAD

**Issue by knownasilya** [tildeio/broccoli-typescript-compiler#59]
Basically I think the last processed file is the only one available in the sourcemaps.

Used here: https://github.com/tildeio/libkit/blob/master/lib/ember-cli-build/typescript.js
Related issue: https://github.com/tildeio/libkit/issues/5
Code you can run: https://github.com/knownasilya/google-maps-drawing-tools (running `npm run tdd` will let you open the browser with the tests.)

**Comment by chancancode** [comment]
This turned out to be a libkit problem (see tildeio/libkit#9).
