### ISSUE TITLE
Typescript 1.7.3 appears to break config loading

### ISSUE THREAD

**Issue by asakusuma** [tildeio/broccoli-typescript-compiler#7]
Neither of these functions appear to exist in 1.7.3: `ts.parseConfigFile()` `ts.convertCompilerOptionsFromJson`
https://github.com/tildeio/broccoli-typescript-compiler/blob/master/index.js#L46-L49

"Cannot load tsconfig.json from ..." gets thrown

**Comment by DanielRosenwasser** [comment]
Sorry about that - I think we renamed the `parseConfigFile` function in 1.7 to `parseJsonConfigFileContent`. Can you make that change and give it a try?

Though, `convertCompilerOptionsFromJson` should be present.

**Comment by asakusuma** [comment]
Yep, I'll take a stab at a PR here. Thanks.

**Comment by rwjblue** [comment]
@DanielRosenwasser - Was `parseConfigFile` considered private API?  If yes, what can we do to ensure we are using public/supported API's here (and avoid minor version breakage like this in the future)?

**Comment by DanielRosenwasser** [comment]
I don't think it was a private API. I just documented the break on https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-17, but we're sorry it slipped under the radar.

**Comment by rwjblue** [comment]
@DanielRosenwasser - Ya, no real worries, I just am ramping up to speed to help maintain here and thought that we might need to figure out a better / more supported path.
