### ISSUE TITLE
Move typescript to peerDependencies?

### ISSUE THREAD

**Issue by mntnoe** [tildeio/broccoli-typescript-compiler#72]
`broccoli-typescript-compiler` currently have a version range as a dependency, making it hard to make it run with a certain version. This has been a source of confused for us on multiple occasions when trying to upgrade typescript. Also, tools like tslint requires typescript as a peerDependency.

Is there a reason typescript is a dependency and not a peerDependency?

**Comment by krisselden** [comment]
Because we test against that version, so this is the version known to work.  It is easy to fork and npm publish a version to your @user scope if you want to try publishing a version using a different version of typescript.

**Comment by mntnoe** [comment]
Ok, thank you.
